# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.CharField(default='', max_length=10, verbose_name='随机编号')),
                ('email_body', models.CharField(default='', max_length=1024, verbose_name='邮件内容')),
                ('email_title', models.CharField(default='', max_length=20, verbose_name='邮件名')),
                ('emial_type', models.CharField(default='普通邮件', max_length=20, verbose_name='邮件类型')),
                ('add_time', models.CharField(default='2019-07-13 Jul-07-13', max_length=30, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'email',
            },
        ),
    ]
