# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_from',
            field=models.CharField(default='', max_length=30, verbose_name='发件人'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_recv',
            field=models.CharField(default='', max_length=30, verbose_name='收件人'),
        ),
    ]
