# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20190713_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_url',
            field=models.CharField(default='', max_length=100, verbose_name='验证链接'),
        ),
        migrations.AlterField(
            model_name='email',
            name='add_time',
            field=models.CharField(default='2019-07-15 14:51:19', max_length=30, verbose_name='加入时间'),
        ),
    ]
