# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_sn', models.PositiveIntegerField(default=0, unique=True, verbose_name='订单号')),
                ('book_owner', models.CharField(default='', max_length=30, verbose_name='订单主人')),
                ('email_booker', models.EmailField(default='', max_length=50, verbose_name='联系邮箱')),
                ('phone_booker', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('book_time', models.DateTimeField(default='', verbose_name='预定时间')),
                ('booker_nums', models.PositiveIntegerField(default=0, verbose_name='预订人数')),
                ('booker_msg', models.TextField(default='', verbose_name='留言信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订单加入时间')),
            ],
        ),
    ]
