# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_sn', models.PositiveIntegerField(default=time.struct_time, unique=True, verbose_name='订单号')),
                ('book_owner', models.CharField(default='', max_length=30, verbose_name='订单主人')),
                ('email_booker', models.EmailField(default='', max_length=50, verbose_name='联系邮箱')),
                ('phone_booker', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('book_time', models.DateTimeField(default='', verbose_name='预定时间')),
                ('booker_nums', models.PositiveIntegerField(default=0, verbose_name='预订人数')),
                ('booker_msg', models.TextField(default='', verbose_name='留言信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订单加入时间')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=30, verbose_name='食物名')),
                ('food_price', models.CharField(default='', max_length=10, verbose_name='食物价格')),
                ('food_desc', models.TextField(default='', verbose_name='食物描述')),
                ('food_class', models.CharField(choices=[(0, '早餐'), (1, '中餐'), (2, '晚餐')], default=0, max_length=10, verbose_name='早中晚餐')),
                ('food_img', models.ImageField(max_length=300, upload_to='', verbose_name='图片地址')),
                ('food_kinds', models.CharField(choices=[(0, '轮播图'), (1, 'Special'), (2, '')], default=2, max_length=10, verbose_name='食物类型')),
                ('is_show', models.BooleanField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否展示')),
            ],
        ),
    ]
