# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmsg',
            options={'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'food信息', 'verbose_name_plural': 'food信息'},
        ),
    ]
