# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmsg',
            name='book_sn',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='订单号'),
        ),
    ]
