# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190705_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmsg',
            name='username',
            field=models.CharField(default='', max_length=30, verbose_name='用户账号'),
        ),
    ]
