# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190703_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='food_class',
            field=models.CharField(choices=[('0', '早餐'), ('1', '中餐'), ('2', '晚餐')], default='0', max_length=10, verbose_name='早中晚餐'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='food_img',
            field=models.CharField(max_length=300, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='food_kinds',
            field=models.CharField(choices=[('0', '轮播图'), ('1', 'Special'), ('2', '')], default='2', max_length=10, verbose_name='食物类型'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='is_show',
            field=models.BooleanField(choices=[('0', '否'), ('1', '是')], default=1, verbose_name='是否展示'),
        ),
    ]
