# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookmsg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=500, verbose_name='聊天内容')),
                ('from_who', models.CharField(default='', max_length=30, verbose_name='发起人')),
                ('to_who', models.CharField(default='', max_length=30, verbose_name='接收人')),
                ('add_time', models.CharField(default='19-07-11', max_length=50, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
            },
        ),
    ]
