# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190711_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmsg',
            name='add_time',
            field=models.CharField(default='2019-07-11 17:48:34', max_length=50, verbose_name='添加时间'),
        ),
    ]
