# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190713_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmsg',
            name='add_time',
            field=models.CharField(default='2019-07-15 14:51:19', max_length=50, verbose_name='添加时间'),
        ),
    ]
