# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, unique=True, verbose_name='用户名')),
                ('pwd', models.CharField(default='', max_length=10, verbose_name='密码')),
                ('add_time', models.CharField(default='0000-00-00 00:00:00', max_length=30, verbose_name='订单加入时间')),
            ],
            options={
                'verbose_name': '账号管理',
                'verbose_name_plural': '账号管理',
            },
        ),
    ]
