# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='模块名')),
            ],
            options={
                'verbose_name': '用户模块',
                'verbose_name_plural': '用户模块',
            },
        ),
    ]
