# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0002_usermanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='add_time',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=30, verbose_name='订单加入时间'),
        ),
    ]
