# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0003_usermanage_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='website',
            field=models.CharField(default='', max_length=50, verbose_name='链接'),
        ),
    ]
