# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0004_usermanage_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱名')),
                ('add_time', models.CharField(default='2019-07-11', max_length=30, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '留言邮箱',
                'verbose_name_plural': '留言邮箱',
            },
        ),
    ]
