# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0005_leavemsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemsg',
            name='topic',
            field=models.CharField(default='', max_length=30, verbose_name='主题'),
        ),
    ]
