# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetting', '0006_leavemsg_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.CharField(default='', max_length=10, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('0', '女')], default='1', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
    ]
